"""BUNKR: username on user, invites removed

Revision ID: 4b314397b9a2
Revises: f49e695321c6
Create Date: 2026-08-22 10:13:28.573962

"""
from alembic import op
import re

import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b314397b9a2'
down_revision = 'f49e695321c6'
branch_labels = None
depends_on = None


def upgrade():
    # Invites are gone: registration is open, so the table has no meaning.
    with op.batch_alter_table('invite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invite_code'))
    op.drop_table('invite')

    # username is NOT NULL UNIQUE, so existing rows need a real value before the
    # constraint can hold. Add it nullable, backfill from the email's local part
    # (de-duplicated), then tighten. A plain server_default would give every
    # existing row the same string and violate the unique index.
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=32), nullable=True))

    connection = op.get_bind()
    rows = connection.execute(sa.text("SELECT id, email FROM user ORDER BY id")).fetchall()
    seen = set()
    for user_id, email in rows:
        base = re.sub(r'[^A-Za-z0-9_.]', '', (email or '').split('@')[0])[:32] or 'student'
        if len(base) < 3:
            base = (base + 'user')[:32]
        candidate, n = base, 1
        while candidate.lower() in seen:
            n += 1
            candidate = f"{base[:32 - len(str(n))]}{n}"
        seen.add(candidate.lower())
        connection.execute(
            sa.text("UPDATE user SET username = :u WHERE id = :i"),
            {"u": candidate, "i": user_id},
        )

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username', existing_type=sa.String(length=32),
                              nullable=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_column('username')

    op.create_table('invite',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=32), nullable=False),
    sa.Column('created_by_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('note', sa.VARCHAR(length=120), nullable=True),
    sa.Column('used_by_id', sa.INTEGER(), nullable=True),
    sa.Column('used_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['used_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invite_code'), ['code'], unique=1)

    # ### end Alembic commands ###
