"""Phase 1 schema

Revision ID: b4a0a92fcbbf
Revises: 
Create Date: 2026-08-16 17:40:14.091157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4a0a92fcbbf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('college',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('adapter_id', sa.String(length=50), nullable=False),
    sa.Column('default_subject_limit', sa.Integer(), nullable=False),
    sa.Column('default_overall_limit', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('student_number', sa.String(length=40), nullable=True),
    sa.Column('roll_no', sa.String(length=20), nullable=True),
    sa.Column('college_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['college.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('report_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('lecture_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('parsed_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_snapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_snapshot_file_sha256'), ['file_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_snapshot_user_id'), ['user_id'], unique=False)

    op.create_table('semester',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_label', sa.String(length=80), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('semester', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_semester_user_id'), ['user_id'], unique=False)

    op.create_table('settings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('overall_limit', sa.Integer(), nullable=False),
    sa.Column('subject_limit', sa.Integer(), nullable=False),
    sa.Column('staleness_days', sa.Integer(), nullable=False),
    sa.Column('advanced_mode', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('holiday',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('on_date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('swap_weekday', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('semester_id', 'on_date', name='uq_holiday_date')
    )
    with op.batch_alter_table('holiday', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_holiday_semester_id'), ['semester_id'], unique=False)

    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('canonical_name', sa.String(length=200), nullable=False),
    sa.Column('lecture_type', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('custom_limit', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('semester_id', 'canonical_name', 'lecture_type', name='uq_subject_identity')
    )
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subject_user_id'), ['user_id'], unique=False)

    op.create_table('timetable_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('raw_name', sa.String(length=255), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'raw_name', name='uq_alias_per_user')
    )
    with op.batch_alter_table('course_alias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_alias_user_id'), ['user_id'], unique=False)

    op.create_table('lecture_instance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('on_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=3), nullable=False),
    sa.Column('first_seen_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('last_updated_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('is_vanished', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['first_seen_snapshot_id'], ['report_snapshot.id'], ),
    sa.ForeignKeyConstraint(['last_updated_snapshot_id'], ['report_snapshot.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'on_date', 'start_time', name='uq_lecture_identity')
    )
    with op.batch_alter_table('lecture_instance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lecture_instance_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lecture_instance_user_id'), ['user_id'], unique=False)

    op.create_table('planned_absence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('on_date', sa.Date(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('planned_absence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_planned_absence_user_id'), ['user_id'], unique=False)

    op.create_table('timetable_slot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['timetable_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('timetable_slot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timetable_slot_version_id'), ['version_id'], unique=False)

    op.create_table('lecture_change',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lecture_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=3), nullable=False),
    sa.Column('to_status', sa.String(length=3), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lecture_id'], ['lecture_instance.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['report_snapshot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lecture_change', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lecture_change_lecture_id'), ['lecture_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lecture_change', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lecture_change_lecture_id'))

    op.drop_table('lecture_change')
    with op.batch_alter_table('timetable_slot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_timetable_slot_version_id'))

    op.drop_table('timetable_slot')
    with op.batch_alter_table('planned_absence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_planned_absence_user_id'))

    op.drop_table('planned_absence')
    with op.batch_alter_table('lecture_instance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lecture_instance_user_id'))
        batch_op.drop_index(batch_op.f('ix_lecture_instance_subject_id'))

    op.drop_table('lecture_instance')
    with op.batch_alter_table('course_alias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_alias_user_id'))

    op.drop_table('course_alias')
    op.drop_table('timetable_version')
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subject_user_id'))

    op.drop_table('subject')
    with op.batch_alter_table('holiday', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holiday_semester_id'))

    op.drop_table('holiday')
    op.drop_table('settings')
    with op.batch_alter_table('semester', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_semester_user_id'))

    op.drop_table('semester')
    with op.batch_alter_table('report_snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_snapshot_user_id'))
        batch_op.drop_index(batch_op.f('ix_report_snapshot_file_sha256'))

    op.drop_table('report_snapshot')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('college')
    # ### end Alembic commands ###
