"""Multi-user: invites, login lockout, unique student number

Revision ID: f49e695321c6
Revises: e6022850ca2a
Create Date: 2026-08-16 18:47:23.796651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f49e695321c6'
down_revision = 'e6022850ca2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('note', sa.String(length=120), nullable=True),
    sa.Column('used_by_id', sa.Integer(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['used_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invite_code'), ['code'], unique=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        # server_default is required: existing rows need a value before NOT NULL
        # can be enforced. Autogenerate leaves it out every time.
        batch_op.add_column(sa.Column('failed_logins', sa.Integer(),
                                      nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('locked_until', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uq_user_student_number', ['student_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('locked_until')
        batch_op.drop_column('failed_logins')

    with op.batch_alter_table('invite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invite_code'))

    op.drop_table('invite')
    # ### end Alembic commands ###
